language: julia

os:
 - linux

julia:
 - 1.3
 - 1
 - nightly

matrix:
 allow_failures:
  - julia: nightly

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ # tags

after_success:
  - julia -e 'if Sys.islinux()
      using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())
    else
      println("Coverage skipped")
    end'
